### ISSUE TITLE
Its not working :[

### ISSUE THREAD

**Issue by GoroGoroNoMilk** [Wynd/MineMineNoMi3#1]
It keeps crashing everytime it loads up it says wylib : minimum version required 1.0 :[

**Comment by Wynd** [comment]
Please provide the MMnM version that you're using..it seems to be an old one since wylib is not required at all for newer builds :/

**Comment by GoroGoroNoMilk** [comment]
Thank You I was being retarded I had the wrong version >.<

**Comment by Wynd** [comment]
Glad it's fixed :)
