### ISSUE TITLE
Sugg - separate Doriki form Stats

### ISSUE THREAD

**Issue by BREEZEXPVP** [Wynd/MineMineNoMi3#105]
**Not a bug this time** , 

### **Idea here** 
My Idea is Separating Doriki from Keep Stats after Death. 
by separating doriki from the normal config keep stats should help player by eating
other fruits , avoid glitches and avoid farming and grinding the doriki again to max .

_example when you have keep stats when you die u keep stats but keep fruit too also can't 
eat other fruits , you can /removedf but you have to be op . can't do this command ingame without the op permission_ .

### **How it should work** 
When bool is true then the doriki will stay even if you die , can eat other fruits and avoid buggs
& glitches 

### **_Config Here_**
 **_Config option_** : Keep Doriki Stats after death = **bool** " _true & false_ "
/-/
**_ Old Config "already using"_** : Keep stats after death , by changing this to only **_devil fruits and bounty 
race factions_** all of that , **_not Doriki_**.

**_That's It thanks for reading my Sugg . have a nice day_**

**Comment by Wynd** [comment]
Added a new option in the config to choose which stats to keep, so closing this issue as fixed.
