### ISSUE TITLE
Bug Goro Goro no mi, Raigo

### ISSUE THREAD

**Issue by Inovactio** [Wynd/MineMineNoMi3#106]
**Describe the bug**
When Raigo is used, the projectile instant kill the user.

**To Reproduce**
1. Eat the Goro Goro no mi
2. Pick Raigo ability
3. Use Raigo under your feet.
4. Don't move & die.

**Expected behavior**
Normally you're not expected to die ( i guess ).

**Screenshots**
![2019-06-01_22 41 05](https://user-images.githubusercontent.com/49309023/58753414-1d7f1b00-84bf-11e9-8f26-03bff6c74e96.png)

![2019-06-01_22 41 30](https://user-images.githubusercontent.com/49309023/58753418-296add00-84bf-11e9-81df-b498b9beedc9.png)

![2019-06-01_22 41 50](https://user-images.githubusercontent.com/49309023/58753421-312a8180-84bf-11e9-937b-899b5b4e68dc.png)

![2019-06-01_22 41 53](https://user-images.githubusercontent.com/49309023/58753427-3e477080-84bf-11e9-89fe-332e4927f6e1.png)

**Additional context**
Area damage doesn't hit you.

**Comment by Wynd** [comment]
Fixed
