### ISSUE TITLE
mole mole fruit crash

### ISSUE THREAD

**Issue by bendoff** [Wynd/MineMineNoMi3#108]
**Describe the bug**
if you hold shift and dig stright down with the mogura tonpo: mogugyo abilty then press e the game crashes

**To Reproduce**
1. eat the mogu mogu fruit 
2. look straight down and whilst holding shift use the mogura tonpo ability 
3. fter digging down about 6 or 7 times press e
4. the game should then immediately crash 

**Expected behavior**
it should just open your inventory.

**Screenshots**
N/A

**Additional context**

**Comment by Wynd** [comment]
Crashlog please ?

**Comment by Wynd** [comment]
Gonna assume it's the same as #112 since no crashlog was provided..closing
