### ISSUE TITLE
another mole mole fruit crash 

### ISSUE THREAD

**Issue by bendoff** [Wynd/MineMineNoMi3#110]
**Describe the bug**
whilst in samehada shotei mode if you equip mole point will crash the game 

**To Reproduce**
1. eat mole mole fruit 
2. as a fishman activate samehada shotei 
3.activate mole point 
4.game will crash

**Expected behavior**
the mole point should turn you into a mole 

**Screenshots**
n/a

**Additional context**

**Comment by Wynd** [comment]
Crashlog please ?

**Comment by Wynd** [comment]
Gonna assume it's the same as #112 since no crashlog was provided..closing
