### ISSUE TITLE
magma fruit breaks bedrock

### ISSUE THREAD

**Issue by bendoff** [Wynd/MineMineNoMi3#111]
magma fruit: ability dai funka and ryusei kazan 
if a player uses either of the two listed abilities on a block of bed rock it will break the bed rock

to replicate
1.eat magma fruit 
2.place a single piece of bedrock down
3.use either dai funka or ryusei kazan  on the bedrock
4.the bed rock will break

**Comment by Wynd** [comment]
Thanks, fixed it :)
