### ISSUE TITLE
Bug happens if you hold an item while transformed into a Zoan

### ISSUE THREAD

**Issue by EthanCH05** [Wynd/MineMineNoMi3#112]
**Describe the bug**
With certain Zoans, when you turn into one of their forms while holding an item, a bigger model of your player with be shown upside down along with the zoan form.

**To Reproduce**
1. Eat Ushi Ushi Giraffe/Zou Zou/Ushi Ushi Bison/Mogu Mogu. The problem doesn't happen with model phoenix.
2. Use Power Point/Zou Point/Hybrid Point/Mole Point depending on which fruit you ate.
3. go into 3rd person view
4. hold an item in your hand
5. you should now see your character model upside down along with the zoan form.

**Expected behavior**
I expected to be able to hold items while being transformed, or at least for this not to happen.

**Screenshots**
![2019-06-16_17 47 23](https://user-images.githubusercontent.com/51891715/59570565-dddc3580-905f-11e9-82c9-9217357d4732.png)

![2019-06-16_17 38 27](https://user-images.githubusercontent.com/51891715/59570569-e92f6100-905f-11e9-8454-384f696c9cda.png)

**Additional context**
I have a few other mods installed, none of which I think would cause this. If you can't reproduce the issue, it's probably on my end.

**Comment by AdmiralSakazuki** [comment]
for me it crashes the game when I go into any transformation and hold an item like venom demon etc

**Comment by Wynd** [comment]
Thanks, fixed it.
