### ISSUE TITLE
darkness fruit

### ISSUE THREAD

**Issue by lewcav** [Wynd/MineMineNoMi3#115]
**Describe the bug**
the darkness fruit doesnt turn off logia invincabilty whilst under its influence 

**To Reproduce**
1. eat the darkness fruit
2. use the any darkness abailites on a person witha logia fruit active, 
3. the person being effected should be effected by this attack but is not, 

**Expected behavior**
the logia user should recieve damage and have his passive abilites dhtu of for a moment, 

**Screenshots**

**Additional context**

**Comment by Wynd** [comment]
Fixed
