### ISSUE TITLE
sinking sand cannit be removed by corrsion 

### ISSUE THREAD

**Issue by lewcav** [Wynd/MineMineNoMi3#116]
**Describe the bug**
the corrsion abilty literally deletes and removes blocks from the players surrounding area and is later thrown out in another attack liberation, the sinking sand block is invulaerable to thiss effect, 

**To Reproduce**
1. use sand fruit to spawn in a bunch of quick sand 
2. eat the darkness fruit 
3. use corrosion to absorb surrrounding blocks
4. see quicksand isnt removed 

**Expected behavior**
the quicksand should be moved

**Screenshots**

**Additional context**

**Comment by Wynd** [comment]
Fixed
