### ISSUE TITLE
crash of zoan fruits

### ISSUE THREAD

**Issue by MXlordsMapone123** [Wynd/MineMineNoMi3#118]
in an update next you can fix this crash that happens when I'm in hybrid form and I'm going to wield some sword and minecraft just crash

**Comment by Wynd** [comment]
🤦‍♂ 
![image](https://user-images.githubusercontent.com/6152557/60401245-1a8f4d00-9b87-11e9-8023-62c52604bf70.png)

**Comment by MXlordsMapone123** [comment]
O:
