### ISSUE TITLE
v3.0 pirate & marine ships not spawning

### ISSUE THREAD

**Issue by jarekszzz** [Wynd/MineMineNoMi3#12]
Hello, I've installed that mod redently. Everything''s working, but when I create world, there is no pirate or marine warships, so how can I get devil fruit on survival? Or, what have I to do to make it working?

**Comment by jarekszzz** [comment]
I looked at the 10k x 10k map of my world, there were no ships.

**Comment by Wynd** [comment]
Yes..there is a bug right now that makes the spawn rate smaller than it's actually supposed to be. 0.3.1 will fix this bug (and many others)
