### ISSUE TITLE
is there a way to make it that you wont lose and doriki or your df when you die?

### ISSUE THREAD

**Issue by GodTheWeeb** [Wynd/MineMineNoMi3#122]
i wanted to know if there was a way to make it so that you wouldn't lose your devil fruit or doriki when you die.

**Comment by Wynd** [comment]
Check the config, the is an option called "Keep stats after Death" which is set on auto by default, set it to full and you'll keep everything

**Comment by GodTheWeeb** [comment]
thanks!
