### ISSUE TITLE
That isn´t an issue

### ISSUE THREAD

**Issue by LitaMasta360** [Wynd/MineMineNoMi3#126]
Sorry, is the 0.6.0 version close to be released?, I know that is not the way to ask, but I dont know how to ask for it...

thanks

**Comment by Wynd** [comment]
You could just ask on the discord server lmao : [link](discord.gg/CYK9xs8)
But to answer I don't know, a lot of things had to be done and will need testing and I am also working on the 1.14 port so it's hard to predict if 0.6.0 is close to it's release or not..
