### ISSUE TITLE
Ope Ope No Mi ROOM Bug.

### ISSUE THREAD

**Issue by DanHeartnet** [Wynd/MineMineNoMi3#17]
Room in Multiplayer sometimes doesn't work at all by not triggering, and it can trigger and bring up Room, but cannot despawn it, but will despawn over time, have been able to reproduce it.

To reproduce, you just go into multiplayer and try activating ROOM, and activate ROOM again, either nothing happens, or it summons it and doesn't go away.

I expect the ability ROOM to appear and be able to be despawned by activating the ability again.

Only seems to happen in multiplayer,

**Comment by Wynd** [comment]
Fixed.
