### ISSUE TITLE
Ope Ope No Mi Water Bug.

### ISSUE THREAD

**Issue by DanHeartnet** [Wynd/MineMineNoMi3#18]
I am able to stand in shallow water without Nausea Debuff, and can get out of it if I am next to a corner.

I have been able to reproduce the bug and the same thing happens each time, with the exception of getting Nausea Debuff one time out of ten of the attempts, but still was able to get out of the water even then.

I expect to be stuck in water with no way out and to have the Nausea Debuff on me.

Happens in both Single Player and Multiplayer.

**Comment by Wynd** [comment]
Updated the water detection code a bit but it might still need some tweaks in the future, closing the issue for now.
