### ISSUE TITLE
is Den Den Mushi cant use?

### ISSUE THREAD

**Issue by ycweng** [Wynd/MineMineNoMi3#19]
im using creator mode to test ur mode, but it seems denden mushi cant use? 
it being a black block

**Comment by ycweng** [comment]
in minecraft 1.7.10, forge-10.13.4.1614 with your mod 0.3.2

**Comment by Wynd** [comment]
Yes it is currently not used for anything and due to some bugs that I had no reason to fix it's shown as a black box

**Comment by Wynd** [comment]
Fixed the rendering bug for it, still has no functionality at the moment but will close as fixed for now
