### ISSUE TITLE
Missing 64 Blocks/Items

### ISSUE THREAD

**Issue by TheLunaGod** [Wynd/MineMineNoMi3#2]
**Hey Wynd I downloaded this mod and I got Impel Down as well, but whenever I load a world it says that I'm missing 64 blocks/items, but I can still continue playing. Do you know what these missing blocks/items are? Thanks if you have an answer.**

**Comment by Wynd** [comment]
Old items that are no longer in that world ( either from MMnM or other mods )...it does not have any impact on the game at all...

**Comment by TheLunaGod** [comment]
@**Wynd Are you planning to add some bosses like Luffy's enemies and stuff? I kinda wanna test the Devil Fruits on some strong enemies. That'd be fun :D**

**Comment by Wynd** [comment]
Yes...new AI is planned for future builds...**after 0.3.0** (the initial release) you could submit a request with the enemies that you think are missing...

~Closing this issue~
