### ISSUE TITLE
 Some special logia can't fly after updating?  Like Moku Moku no Mi

### ISSUE THREAD

**Issue by zzz11303** [Wynd/MineMineNoMi3#20]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Wynd** [comment]
Don't wanna sound rude but...those fields were there to be completed or deleted in this case...
As for the actual question, the flying feature is currently on-hold for all logias and has been like this since 0.3.0 with no ETA on when it's going to be added back.
