### ISSUE TITLE
A Issue Report To Start The Pirate Age Of Minecraft 

### ISSUE THREAD

**Issue by WolfHoundProphet** [Wynd/MineMineNoMi3#22]
- Improvement in the Player's World and Game play with Mine Mine No Mi 
Being a video gamer and One Piece fan, I played various versions of the series whether it be on Roblox or bit fighting games. I want to find the best available game to recreate the experience of the show. 
Mine Mine No Mi compared to the recent OP Craft is superior in amount of devil fruits and development.

- New Additions and Updated Movements

However from the older versions of the mod to the newest updated version, I experienced movement has been downgraded and the spawn rates of the Ships that contain the Chests. Movement is a big thing too, with a devil fruit flying and or teleportation is important, like the "Moku Moku No Mi"  has the "Smoke Launcher" why limit the ability movement. One should be added to most devil fruits. A addition if possible would "Logia Effect". Which would be nice if they could highlight any projectile or attack damage that hits the player and then once again retains the regular player. If possible if they player could completely embody being their element physically. It would be inspiring. 

- Upgraded Devil DF Abilities , Weapons , or Suggested DF

- Moku Moku no Mi : extended Flight and Smoke Dash, more offensive attacks like 
- Pika Pika No Mi : Visual effect when Teleporting
- Goro Goro No Mi : Teleportation, Speed. These offensive abilities are amazing. 
- Mera Mera No Mi: All is needed is Flight.
- Gomu Gomu No Mi: Galting was a effective and often used technique of luffy. A Physical or Visual changing when using gears especially" Gear Second" smokey aura maybe
- Bane Bane No Mi: Spring Legs
-Tori Tori No Mi: Phoenix Fruit and Ancient Zoan
- Inu Inu No Mi: Wolf Fruit And Zoan
- Yomi Yomi No Mi: Revive Fruit : Allows to choose whether to Respawn or continue living. Or Soul may apear out of body.

This is going out to a creator from a fan who really appreciates your work and vision that you have blessed us with. Keep working hard and please update this game to the latest and make it the very best anime mod. One Piece is a passion and your mod really helps connect that world and joy to our fingertips!

**Comment by Wynd** [comment]
Some of these suggestions were implemented in the latest version ([changelog can be found here](http://pixelatedw.xyz/changelog)) as such I will close this issue, (for the few ones that were not added right now, they've been added to the to do list and will most likely be implemented soon
