### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Eron12395** [Wynd/MineMineNoMi3#23]
When ever i start the game it crashes and i get this crash report:

The game crashed whilst initializing game
Error: java.lang.IllegalArgumentException: Duplicate enchantment id! class xyz.pixelatedw.MineMineNoMi3.MainEnchantment and class noppes.npcs.enchants.EnchantDamage Enchantment ID:100

I don't know what to do. Please help!

**Comment by Wynd** [comment]
Morning,

It's an easy fix really, in your .minecraft folder you should have a config folder go in it and open the mineminenomi.cfg file in here you need to edit these 2 lines

    I:"Enchantment ID : Dial Impact"=100
    I:"Enchantment ID : Kairoseki"=101

Change the numbers from 100/101 to pretty much any number between 63 (below it there are vanilla ids) and 255 until the crash is gone.
