### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by Yakend** [Wynd/MineMineNoMi3#25]
**Describe the bug**
Game crashes :/

**To Reproduce**
1. Grab yami yami no mi and hie hie no mi (probs would work with only hie)
2. go into creative
3. fly close to water at to speed
4. game crashes
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 21/09/18 9:35 PM
Description: Exception ticking world

java.lang.IllegalStateException: TickNextTick list out of synch
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:503)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:181)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:503)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:181)

-- Affected level --
Details:
	Level name: (NONE OF YOUR BUSINESS BOI)
	All players: 1 total; [EntityPlayerMP['YakendYT'/441, l='one penis', x=-73.65, y=64.05, z=111.48]]
	Chunk stats: ServerChunkCache: 680 Drop: 0
	Level seed: 137869769
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-148,64,184), Chunk: (at 12,4,8 in -10,11; contains blocks -160,0,176 to -145,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 22233 game time, 9735 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 126630 (now: false), thunder time: 152501 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 285187800 bytes (271 MB) / 754974720 bytes (720 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	mineminenomi{0.3.2} [Mine Mine no Mi] (Mine+Mine+no+Mi+-+1.7.10+-+0.3.2.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['YakendYT'/441, l='one penis', x=-73.65, y=64.05, z=111.48]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Wynd** [comment]
Out of curiosity, is this happening 100% of the times ?. From the code bit that caused the crash it doesn't seem to be related with any block placement but rather with entities updating.
I've tested for a bit (even as a fishman just to make sure) and it didn't happen ...so the crash report title "// But it works on my machine." is 100% accurate again...

**Comment by Wynd** [comment]
Old
