### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by TheBakersMen** [Wynd/MineMineNoMi3#29]
I don't use GitHub so I'm sorry if this is posted in the wrong area. 

Just wanted to ask if it would be possible to include a no-griefing option in the config, keeping the explosions but not actually destroying whole parts of the map. Turning off mob-griefing doesn't do anything to some fruit abilities (yami, gura, etc), so it forces me to prevent people from using those otherwise the islands of the custom map just get destroyed. 

If this is possible, I know Yami requires absorbing blocks to spit back out, and it may be more trouble than it's worth but perhaps instead of actually removing whole sections of the land it just duplicates those blocks but doesn't actually remove them? If this isn't possible I understand.

Thank you for your time.

**Comment by Wynd** [comment]
Yeah got this suggestion a lot...will most probably become a thing soon but it'll break a lot of the abilities, obviously, like you've said some of them are dependent on breaking or destroying blocks..

**Comment by MXlordsMapone123** [comment]
wynd mine mine in mi and the best mod of one piece already created already tested the new version 0.4.0 plus you can add flight to the logia in the next update and also haki I would be very grateful

**Comment by MXlordsMapone123** [comment]
wynd I researched it is after a while I searched for devil fruits that can be added in the future= chiyu chiyu no mi {fruit of the cure}, ishi ishi in mi {fruit of the stone}, mero mero {passion fruit} mochi mochi no mi {mochi fruit}, supa supa no mi {blade fruit}, yomi yomi no mi {fruit of the resurrection},hito hito no mi{buddha model}, neko neko no mo {model leopard}, zou zou no mi {mammoth model}

**Comment by Wynd** [comment]
Added the original suggestion
