### ISSUE TITLE
Hello! I wish you could help me in the problem that is happening to me. I'm creating a modpack that contains this wonderful mod plus the problem is that when I die or another player dies the Akuma no mi that I as disappears, I wanted to make the akuma no mi does not disappear and so I still get the power of it  I want a way to change when I die I do not lose akume no mi

### ISSUE THREAD

**Issue by lukarelio** [Wynd/MineMineNoMi3#31]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Wynd** [comment]
You know...the title should be something simple, and the description of the bug should contain all the details...whatever...in your config folder you should have a "mineminenomi.cfg" file. Open it and change this line from : 
S:"Keep stats after death"=auto
to 
S:"Keep stats after death"=full

**Comment by Wynd** [comment]
Probably fixed...
