### ISSUE TITLE
Ship spawning seems to be broken in 0.4.0

### ISSUE THREAD

**Issue by tabeh** [Wynd/MineMineNoMi3#34]
The ships are way too rare. I traveled over 20k blocks, and i could only find one marine ship without any crates or keys in the chests. I even tried editing the config, but the ships don't spawn even if i set the modifier to a thousand or even a million. I'm kinda new to the mod, and the changelogs say that the rates are increased now ? I don't know if i'm missing something, but if this is the intended spawnrate, then i don't know how people would've found any ships before, so i feel like there's something wrong.

**Comment by tabeh** [comment]
well, setting the modifier to 100 or below seems to fix the problem.

**Comment by Wynd** [comment]
Pretty much..if they spawn then it's not broken...the config value is a multiplier so 100 is the maximum (x100 times more ships)...so probably larger values simply break this but I haven't tested..anyway you can keep it to 15-20 and there should be plenty of shits..the idea why they're so rare is that in the future there will be more ways to obtain devil fruits or to encounter enemies so ships will just be 1 of the choice if, for example, you're on water more than on land
