### ISSUE TITLE
bug mine mine no mi server

### ISSUE THREAD

**Issue by CL3M3NT0** [Wynd/MineMineNoMi3#35]
**my screen was rotate **
my screen was rotate after in my server i have use zoan devilfruit

**To Reproduce**
1. Go to 'inventory'
2. Click on 'zoan'
3. eat 'marco devil fruit'
4. game crash
5. after crash my screen was rotate and i take damadge all the time

**Expected behavior**
a way for solve this bug in serveur

**Screenshots**
![capture](https://user-images.githubusercontent.com/44667872/47844311-60123500-ddc2-11e8-86ce-60266cfedd18.PNG)

**Additional context**
i need of this because i make server one piece with this mod

thanks

**Comment by Wynd** [comment]
If it crashed please also add a link to the crashlog otherwise I won't be able to fix it...Tori Tori no Mi has been ate 1000+ times and this is the first time it crashes so it either is some mod incompatibility or something completely unrelated.

**Comment by CL3M3NT0** [comment]
The bug was at server and solomode .. so i have put mods : Archimed ships,
Chisel, World Edit..
But i think the probleme was come to world edit.. probably..
I Will share to you the report crashes

**Comment by CL3M3NT0** [comment]
crash-report:

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 01/11/18 11:01
Description: Initializing game

java.lang.IllegalArgumentException: Duplicate enchantment id! class
xyz.pixelatedw.MineMineNoMi3.MainEnchantment and class
noppes.npcs.enchants.EnchantDamage Enchantment ID:100
at net.minecraft.enchantment.Enchantment.<init>(Enchantment.java:53)
at
xyz.pixelatedw.MineMineNoMi3.MainEnchantment.<init>(MainEnchantment.java:10)
at xyz.pixelatedw.MineMineNoMi3.lists.ListEffects.init(ListEffects.java:15)
at xyz.pixelatedw.MineMineNoMi3.MainMod.init(MainMod.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at
cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at
com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at
com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at
com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at
cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
at
cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at
com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at
com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at
com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at
cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
at
cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is
as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
at net.minecraft.enchantment.Enchantment.<init>(Enchantment.java:53)
at
xyz.pixelatedw.MineMineNoMi3.MainEnchantment.<init>(MainEnchantment.java:10)
at xyz.pixelatedw.MineMineNoMi3.lists.ListEffects.init(ListEffects.java:15)
at xyz.pixelatedw.MineMineNoMi3.MainMod.init(MainMod.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at
cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at
com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at
com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at
com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at
cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
at
cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at
com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at
com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at
com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at
cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
at
cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle
Corporation
Memory: 420252880 bytes (400 MB) / 754974720 bytes (720 MB) up to
2147483648 bytes (2048 MB)
JVM Flags: 8 total;
-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
-Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC
-XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50
-XX:G1HeapRegionSize=16M
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine
OptiFine_1.7.10_HD_U_E7 7 mods loaded, 7 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized
'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E'
= Errored
UCHI mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
UCHI FML{7.10.99.99} [Forge Mod Loader]
(forge-1.7.10-10.13.4.1614-1.7.10.jar)
UCHI Forge{10.13.4.1614} [Minecraft Forge]
(forge-1.7.10-10.13.4.1614-1.7.10.jar)
UCHI ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships]
(ArchimedesShips-1.7.1.jar)
UCHI chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar)
UCHI customnpcs{1.7.10d} [CustomNpcs] (Custom-NPCs-Mod-1.7.10.jar)
UCHE mineminenomi{0.3.2} [Mine Mine no Mi] (Mine Mine no Mi - 1.7.10 -
0.3.2.jar)
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35'
Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this
crash. You can safely ignore these errors. And update forge while you're at
it.
Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
LWJGL: 2.9.1
OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35,
NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate
blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
OptiFine Version: OptiFine_1.7.10_HD_U_E7
Render Distance Chunks: 24
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: (internal)
OpenGlVersion: 4.6.0 NVIDIA 391.35
OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 4

**Comment by Wynd** [comment]
They're obviously 2 different crashes somewhere...the one that you've mentioned above happens when you open the server, and it would've not let you go any further before solving it (basically stopping the server before finalizing the opening) and it's fixed like so : 

> In your .minecraft folder you should have a config folder go in it and open the mineminenomi.cfg file in here you need to edit these 2 lines
> 
> I:"Enchantment ID : Dial Impact"=100
> I:"Enchantment ID : Kairoseki"=101
> 
> Change the numbers from 100/101 to pretty much any number between 63 (below it there are vanilla ids) and 255 until the crash is gone.

However in the original post you're already on the server so this is not the cause, there must be another crash log there.

**Comment by CL3M3NT0** [comment]
Ok thanks, but what is the 2 problème ? In m'y crash report of my server?
And i have question for your mod mine mine no mi : do you think upgrade
mod? For exemple add new devilfruit (in the arc Bigmom, 75% of child bigmom
have devil fruits: candy , furnase, cracker, katakuri?

**Comment by Wynd** [comment]
Well I have no idea what the second problem is tbh...but yeah you should have a second crashlog or something, if you can reproduce it 100% you can just empty the crashlog folder, reproduce it again and then give me that crashlog.

Also the mod is constantly updated...and new stuff is added, but right now the next version (0.4.1) will be dedicated to small changes and fixing bugs, as for the big mom arc DFs..the idea is that we won't add any new devil fruit that wasn't shown in the anime as well, even if the manga showed them years ago, so to avoid spoilers. the big mom arc is not yet completed in the anime but some fruits have been shown, so don't worry those will come soon :)

**Comment by CL3M3NT0** [comment]
Aaahh ok i understand ! Ok ok Nice, so if you add new item, can you add
"poisseine" or stéroïde ? Is it in the arc of fishefman, with hoddy
 and in minecraft i think you can add this : the gays eat stéroïd, he gets
speed, jump boost and strenght and if he eat 5 stéroïdes he died !  x)
And ok for arc of mama its good idea or sure

**Comment by CL3M3NT0** [comment]
hello guy, i have question, can you make version of mine mine no mi in
1.10.2 for me?
please guy i make server pirate and this is inspired of One Piece !
and i use your mod but your mod is in 1.7.10 and.. please can you make for
me mine mine no mi in 1.10.2?
if you make that. i will to make publish your mod and your twitter in my
server ! and i will make a boss with your name are you okay?

**Comment by Wynd** [comment]
Umm no, there are multiple reasons why I don't wanna touch those versions, the mod will stay for 1.7.10 until forge 1.13 is released at which point the mod will be available for both versions and no others. There's a LOT of work to port a 1.7.10 to anything 1.8+ and porting it for an old version just for a server is simply not worth it time-wise.

**Comment by CL3M3NT0** [comment]
Hmm.. ok ok i understand..
When do you make new update for mine mine no mi?

**Comment by Wynd** [comment]
Hopefully fixed after the recent updates
