### ISSUE TITLE
Enchantment Bug with mineminenomi weapons

### ISSUE THREAD

**Issue by Notkuma** [Wynd/MineMineNoMi3#36]
**Describe the bug**
Not being able to enchant the mineminenomi swords on servers

**To Reproduce**

**Expected behavior**
I would like to see this bug fixed in the later updates for servers.
**Screenshots**
![2018-11-07_15 03 09](https://user-images.githubusercontent.com/44848924/48157786-99551400-e29e-11e8-88d0-01d528a0a8cd.png)
![2018-11-07_15 03 42](https://user-images.githubusercontent.com/44848924/48157798-a5d96c80-e29e-11e8-9160-e3d501bd79e4.png)

**Additional context**
it works in single player but idk why it doesnt wanna work on servers (well not the enchantment table but the anvil works)

**Comment by Wynd** [comment]
Weapons will now be enchantable, however only the weapons that can be obtained normally, nothing I can do about this at the moment, will further work on this in the future
