### ISSUE TITLE
Devil Fruit users injured from the users attack

### ISSUE THREAD

**Issue by Notkuma** [Wynd/MineMineNoMi3#37]
**Describe the bug**
i ate the ito ito no mi and i am being affected by my own technique (birdcage/Torikago) is also 

**To Reproduce**

**Expected behavior**
i wish for this to be fixed in later updates

**Screenshots**
![2018-11-09_07 21 09](https://user-images.githubusercontent.com/44848924/48262466-9b2eec80-e3f0-11e8-8a8b-c2d13435e2fd.png)
![2018-11-09_07 18 52](https://user-images.githubusercontent.com/44848924/48262472-a08c3700-e3f0-11e8-8d8e-c630caea10b6.png)
![2018-11-09_07 19 17](https://user-images.githubusercontent.com/44848924/48262476-a2ee9100-e3f0-11e8-841f-d84224a97ebf.png)
![2018-11-09_07 19 31](https://user-images.githubusercontent.com/44848924/48262486-a84bdb80-e3f0-11e8-8a3b-e3837c290896.png)
![2018-11-09_07 20 54](https://user-images.githubusercontent.com/44848924/48262490-ad108f80-e3f0-11e8-8e9b-669d6d23f4b5.png)

**Additional context**
ate ito ito getting wounded from my own technique and birdcage/Torikago goes invisible

**Comment by Wynd** [comment]
Fixed
