### ISSUE TITLE
List of Abilities is Cut Off

### ISSUE THREAD

**Issue by LittleMidori** [Wynd/MineMineNoMi3#38]
**Describe the bug**
When you eat multiple Devil Fruits and then go to the list of abilities, the last ability will be cut off partly.

**To Reproduce**
1. Launch Minecraft with the latest mod installed
2. Join or create a new world
3. Eat at least 2 Devil Fruits (Yami is obviously one of them)
4. Push the R (by default) button and open the Abilities tab
5. If you have to scroll down to see all the abilities, the final ability should partly be cut off

**Expected behavior**
It should show the ability completely

**Screenshots**
![2018-11-17](https://user-images.githubusercontent.com/45116243/48657902-25351180-e9fe-11e8-9aca-25b456eee22e.png)

**Additional context**

**Comment by Wynd** [comment]
To be honest it seems to only happen with certain combinations for example I've tried with Yami and Pika and the last ability is like 1 or 2 pixels cut, but it's a problem anyway, thanks for reporting it :3 will fix it asap

**Comment by Wynd** [comment]
Fixed
