### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Fynja** [Wynd/MineMineNoMi3#40]
The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.IllegalArgumentException: Duplicate enchantment id! class xyz.pixelatedw.MineMineNoMi3.MainEnchantment and class noppes.npcs.enchants.EnchantDamage Enchantment ID:100

**Comment by Wynd** [comment]
![image](https://user-images.githubusercontent.com/6152557/48972574-c55dec80-f035-11e8-9409-ebc13f60ea22.png)

**Comment by Wynd** [comment]
Probably fixed
