### ISSUE TITLE
Small Suggestion

### ISSUE THREAD

**Issue by TheBakersMen** [Wynd/MineMineNoMi3#44]
Would it be possible for you to add weapons made of seastone that have the same property - capable of damaging logia? I ask because making a custom map/server to play on with friends, the NPCs are unable to damage logia because the only way to do so is with haki, and ranged weapons I can get working. I'm only asking for a melee option, Jitte is an example of one of these seastone weapons.

Thanks

**Comment by FGpisces** [comment]
Hi,
in previous versions (0.2.4 I think), Kairoseki was an enchantment, which allowed the weapon to hit logias, this will be added back. Also, some more weapon, like the Jitte will be craftalble soon

**Comment by MXlordsMapone123** [comment]
i havê suggestion you can put a system to activate and deactivate the intangibility of the logias during the gameplay

**Comment by LucasMeierTurtor** [comment]
Estaria bueno que las frutas logia contengan la logia, y me gustaría que cuando tengas una fruta en la que una de sus habilidades te permita volar que no te hagas daño al caer de muy alto.

**Comment by Wynd** [comment]
Since 0.5.1 you can use the anvil and add a Kairoseki enchantment to any weapon, which will in turn hit logias. Closing as fixed.
