### ISSUE TITLE
Yet ANOTHER suggestion Part 3 (I'm sorry, this one is huge) 

### ISSUE THREAD

**Issue by Mind101** [Wynd/MineMineNoMi3#48]
This is probably the best suggestions I've ever come up with... so enjoy. :)

- The **Doa Doa no mi**, an interesting fruit... so many possibilities with this one... With this fruit in minecraft you can escape anything dangerous, It's a pretty good fruit for evasive people who hide. Anyways, my suggestion for this one... pretty much, you have **3** abilities... **First** Ability Let's you put a door on the ground, once you enter it you will have an intangible effect whilst being on the ground, so you can pretty much travel to a cave, or travel a good distance pretty quickly, one you get out of the ground you will stop being intangible, also extra bonus if you actually add a transparent door block everytime you use this fruit. **Second** Ability is pretty complex, punch a person with the fruit and their head will spin around, they won't be able to see what's going on. **Third** and Last ability, **Air Door!**, You can punch the air with the fruit in which will allow you to go into a "Different dimension" where you can have your little fun, nobody can see you once you're in this "dimension" so you're free to roam the world, pretty much... you punch the air and a door shows up, go through it and you instantly go intangible, the sky turns green (Which shows you're in a different dimension) like this...
![image](https://user-images.githubusercontent.com/45213298/49335173-67815580-f59d-11e8-915a-52b1ee7dfbe8.png)
and you can move around and be intangible all you want, you can't hurt anything or be hurt, all you do is look around... Once you've scouted the area and had your share of fun you can click the ability again which summons a door which brings you back to the normal world or makes you un-tangible in minecraft terms. 

- The **Mero Mero no Mi**, This one was pretty useless in the older versions of the mod, but now it can have its time to shine... **Mero Mero Mellow**, this Ability launches a huge heart at enemies, any enemy who is below 100 doriki or weak will be turned into stone, or in minecraft terms... turned into stone blocks. While they're in that state you can mine the stone blocks in which will kill the opponent, or... you can save them with another ability **Mezameyo!** which will turn them back to their normal state, here is the twist... once you bring them back to their old state, instead of trying to attack you again... the opponent will fight for you... this is only for singleplayer but there's another way to add this to multiplayer, the person who the ability was used on cannot hurt the person that freed them for 1 minute. **Pistol Kiss** is the same thing as **Mero Mero Mellow** but much faster and can be added with Haki which will get more stronger mobs or players turned into stone.

- The **Soru Soru no mi**, So you mentioned how the fruits need to be shown in the anime then you'll add them, well here's one... Big Mom's fruit. **First** Ability, For this one you have to... prepare. You need a flint and steel or a mera mera no mi user, anything that creates fire, pretty much this ability allows you to put a fraction of your "soul" into the fire which makes a very strong ally that flies around and shoots stuff at people... that's pretty much it. **Second Ability**, this one took me a while to think of... Pretty much... once you use this ability you won't be able to move, it will create an invisible "room" which detects which entities or mobs are in the circle, if the mobs in the circle stand still for even a second... they will lose 30 health and that health that everyone combined will all go to you, this is pretty balanced because while you use this ability you're open for any surprise attacks... and the opponent could simply... well... not stay still, So its something like this.
![image](https://user-images.githubusercontent.com/45213298/49335151-a8c53580-f59c-11e8-8b7c-e911f93171ff.png)
Yonko fruits are powerful, accept that. They just need their rarity buffed up more than the other fruits. 

- **Haki**, now I talk about Haki a lot... and I mean a lot... you can tell I really like it, it's my favorite thing in one piece, something about it is so interesting... So when I played this mod and got haki... idk it felt like there was something missing, I know more stuff will be added but I'm going to include what I think is missing, I might say stuff I've said before but I'll add more context to it. **Busoshoku Haki**, so in the mod to get Busoshoku you have to kill mobs, which get's really repetitive and boring... You have to kill somewhere around 30k mobs to finally get busoshoku, there has to be another way to get it... a way that is unique... and I came up with the perfect idea, this is gonna be long so get comfortable. 
- **Busoshoku Haki**: You can find and pay a Busoshoku Haki Master in the world, like you mentioned... you can pay with your bounty or Beli in a later future, so this adds more usefulness to that. Anyways, you either pay the master a lot and I mean... A LOT of Beli or just show him your bounty, he will decline if your bounty is below a certain number. Anyways, just like the sword master, he will give you quests... There will be a counter on his interface as well, that is labeled "Chance of Busoshoku Haki: #" This will slowly go up every mission you do. 
**Quest Ideas**: The **first** quest he will give you, he will tell you to go to a forest biome and kill the animals there... After you find one you will start to see giant strong animals, once you successfully kill them all, he will give you the next quest. **Second** quest, he will ask you to reach build limit and stay there for 3 minutes, this tests your willpower and determination. **Third** Quest, He will ask you to almost die 5 times, you have to be at 1 heart, 5 times... It's pretty self explanatory why this is here. *Forth Quest*: He will ask you to try to beat, the beast of the Jungle... A huge monkey that is very tough to kill, you have to go to the jungle again. 
These 4 quests loop for about 10 times with different dialogue of course... after the 10 times you have to do more of these 4 quests, however... there will be a random chance that during these quests or while you're fighting something that you'll awaken something called "Incomplete Haki" which won't be the completed version... randomly your fist will go black while you're fighting and turn off after a while... do 5 more looped missions after the 10 and your Master will give you a final mission... to fight him. While you fight him you will "observe" and he won't stop fighting you until you randomly awaken your **Busoshoku Haki** while fighting him, he will stop fighting you once you awaken. After that you don't have to see him again, I guess you can pay him visits I guess... After that your Busoshoku Haki will be "weak", you strengthen it by using it. Now, after you awaken you will gain access to a new keybind, the Haki Customization... This let's you choose which body parts you want to put your haki on and whatever you choose will be where your haki goes, each part you choose will have different effects... 
**Fists**: Well... it is the default right now, you just deal more damage...
**Legs**: This one I guess could work with Black leg style if it gets added.
**Torso**: Will protect you from Blunt attacks, a lot of resistance.
**Head**: Decreases damage from Kairoseki or normal bullets or any skills from the Sniper skill tree. 
The fists one is what you start off with, as you grow your buso haki you will be able to use all of them once at a time... once your buso gets higher than ever then you'll be allowed to use all of these at once... might give you a little nausea afterwards because you used too much haki or willpower to do that, then again you can train your buso to get rid of that weakness. After all that work you will be an iron killing machine. Also, like I mentioned before, as your haki grows you will start to get powerful looking particle effects. 
**Weapons with Buso Haki**: All the weapons in this mod at one point will all have durability and are going to be limited, however... once you get haki and mix it with a weapon then the durability will be unlimited, it will never break. When Buso Haki is used on a sword, it would be great if it had really powerful looking particle effects, kinda like this. 

![main-qimg-6bdeb398601bf55fbebbba4ea19431c0](https://user-images.githubusercontent.com/45213298/49335139-453b0800-f59c-11e8-8fb6-0c4309496706.jpg)

- **Kenbunshoku Haki**: You can find a Kenbunshoku Haki Trainer and just like the Busoshoku, you can pay him Beli or with your bounty... Now... once you buy him he will send you on a couple of quests. 
**Quests**: **First** Quest, he will ask you to grab 3 leather and show him, then he will tell you to put it in some pattern to craft a blindfold, he is then gonna tell you to put that blindfold on for a minecraft day and go outside and survive... you will be able to see a little bit because... it's leather... but it will still be really difficult to stay alive with those on. When you finally survive and get through it, you will have to talk to him again... he will tell you that you cheated and will tell you to bring 3 iron to him... you will then make an iron blindfold, same thing happens, survive for a minecraft day with them on... He will say that you cheated once again and ask you to bring 3 diamonds... you craft a diamond blindfold, same thing happens. He will believe you this time since it's diamond, now he will give you a different mission... **Second** Quest, he will tell you to fight an invisible person just outside of his dojo... once you've defeated the person you talk to him again, in which he tells you that there's 3 more... successfully kill those 3 (It's very difficult) and proceed to the next quest. **Third** Quest, now he will tell you that he will shoot you with a gun and to try to dodge 40 bullets in a row, then he will ask you to dodge 15 bullets with your leather blindfold on (This is very difficult), once you've done that you will get the next quest. **Forth** Quest, your master will tell you that there is a weak pacifista outside of the dojo, he will ask you to beat him, he will shoot laser beams... not very fast ones but yeah... he's still very strong. 
**After** those 4 quests they will all loop, this time with tougher challenges than the last one, the Invisible people will be stronger... mobs will spawn around at an abnormal rate when you're blindfolded... and Pacifista will be stronger. These quests will loop at least 3 times... after the 3 loops you will randomly start dodging some of the things thrown at you from the enemies and will start to see them, it happens randomly. After that, you do the loops 3 more times and will talk to your Master, he will ask you to fight him, he uses a very fast gun to shoot you and 2 invisible people will come at you as you fight him too... but while you're fighting him you will randomly dodge more of his shots as the fight drags on, until you dodge every single one of his shots and also see the invisible people coming at you. After that he will stop fighting you and so will the invisible people... you will then have full control of when you use **Kenbunshoku Haki** now, this haki is different than my busoshoku haki suggestion tho... it brings 2 abilities to the table, they're pretty separate abilities within the same haki, 
**Sensing**: Sensing will allow you to sense players, mobs, as you know... but the more you use it the longer you can sense, until you can sense a whole island... this ability can be charged for the distance you want to sense... a meter will show up that will tell you which is high and which is low while you hold the ability down or charge it. It can see invisible people and intangible people, which makes this Doa Doa no mi's worst nightmare. 
**Dodging**: Unlike the sensing this one has a huge limit to it's evolution or progression... for balancing reasons. This ability when Shift + Kenbunshoku Haki ability is pressed will make you dodge everything for 3 seconds. This one can only be upgraded to 2 levels, the 2nd level will make you dodge everything for 6 seconds but have a bigger cooldown... pretty balanced I'd say, so people can use it wisely... 
**How dodging can work... in programming terms**: Well... it's pretty simple, make it so when a projectile or punch hits you as soon as it registers the punch it won't hurt you and you'll move side by side instead... Here is an example. 

![dodgy dodge](https://user-images.githubusercontent.com/45213298/49336070-e67f8980-f5af-11e8-92f4-a49dc309021f.gif)

As you can see they can't hit you and when they do, you just move side to side, maybe you can make this a bit better... make it seem like you're more dodging? However, there should be things you have to dodge on your own accord, take the Raigo for example... that shit is huge... so you can't dodge it with Observation, instead you get the hell out of there. 

- **Haoshoku Haki**: I think I said something about this before, I still think this is a good idea but I'll say it again... summarized... You have a 1% chance when you almost die to awaken haoshoku, make it happen to you 3 more times and you can use it, the more you use it the stronger it gets... if you fight an opponent with Haoshoku it will cause a clash, whoever has the strongest wins and the loser get's knocked out for 3 seconds. 

- **Electro Fighting Technique**, now I'm sure you don't get this one suggested often or at all... Pretty much its the fighting style that Carrot uses. This is literally a much smaller version of Goro Goro no mi, pretty self explanatory. If a mink race were to be added, this should be the race abilities it should have. 

![91f74f71d5408095e8ca62399bb7ba0b9ce1887br1-452-250_hq](https://user-images.githubusercontent.com/45213298/49336195-66a6ee80-f5b2-11e8-965c-0361bced491a.gif)

- Make it so that Abilities get bigger depending on your **mastery** of the technique, like if you had rankyaku it would get bigger and more destructive than when you first learned it, It adds progression. 

- For **Cursed Swords**... Make it so it has a chance to hurt you... like a small tiny chance, make it hurt you around 1-6 hearts of damage. Once you use Buso Haki on them, they stop being cursed since buso is literally your willpower, putting your willpower on a whole sword... and a cursed one at that... should negate the curse. 

- **The Way of the Voice**, pretty cool ability. Make it so there's a 0.5% chance you get it once you begin a new world, and once Sea Kings are added you can hear them talk... but make it an easter egg, like you would hear them talk about stupid stuff or about the newspaper or smth, that would be funny. 

- The **Nagi Nagi no mi**, make it the most common fruit... even though it's not too bad if you're trying to trip out the guy training his Kenbunshoku Haki with the blindfolds, if you wanna be an asshole... this is the fruit for you. :)

- **The Mira Mira no mi**, This has to be the fruit I'm most waiting for, not only do you have a whole dimension to yourself but you can travel through mirrors. **First** Ability, you can mark any glass anywhere and put a marker on that glass... now you press the ability again and you teleport to that piece of glass you marked. **Second** Ability, It's just a world all to yourself, you can teleport to marked glass in this world too. **Third** Ability, If you time it right, when an ability comes flying towards you, you can throw a big mirror at it and it will reflect it back, works on all abilities that have projectiles, also add a cool little thing where if someone used Gura Gura no mi and you used the 3rd ability to reflect it... the mirror breaks. 

- The **Giro Giro no mi**: You thought this fruit was hard to implement because it included reading people's thoughts? HA, it's still useless tho. Pretty much, all you can do with this fruit is see how much health someone has... I mean, this is useful for a server that doesn't let you have damageindicators... I guess. 

- If you can... make it so swords if the're on the 1st slot go on your waist. This way, when people see you in multiplayer with a sword they know you're a swordsmen and come up with a way to counter you. Nah, it's because it looks cool asf, I'm sure you'll agree. 

- I feel like there should be more "manipulating" the terrain than manipulating the people inside your **Room**, I'm talking about the **Ope Ope no mi**... make it so when you activate your **room** you can mess with the blocks inside the **room** with a new ability, and make it so you can throw them at people, or maybe add an ability that lets you select one or more blocks by holding down the mouse button... that would be pretty fun and some creative stuff can be made with this. 

- Would be pretty cool if the particle effects change depending on what the logia gets hit with, if he gets hit with a sword without haki it makes a slash-like particle effect pattern and fist is just... normal. 

- Stances should be a thing, I mean it's just a stand still animation... you're not really "moving" anything in a stance, like if you ready your sword you will break into a cool looking stance if you stay still, if you move you'll just be normal. 

- Make it so there's slots for putting weapons, there's a left slot for left hand weapon, a right hand slot if you want to dual wield put weapons on both... even a mouth slot if you wanna be Zoro. 

- Make it so if you get someone's heart with the Ope Ope no mi and you dump it in lava, the person instantly dies. 

- Add Beer and Whisky, like why not. 

- Add an Ability to the sniper class, where... you... can... snipe people, it's literally called the sniper class and shooting cactus was added before actual sniping. Seems legit. 

- Make it so you can add a pigeon on your shoulder, I never realized how badass having a pigeon on your shoulder makes you look... until Lucci came along. 

- You know what would be amazing? if you used Conqueror's haki on a Sea King... and you rode it. Seriously, this needs to happen... This is the true Conqueror's life, riding the beasts of the sea no problem, don't tell me you don't think that wouldn't be cool. :p 

- Would be cool if there were random poneglyphs laying around in the world, just for lore sake. 

- Random Events should be added to den den mushi, It happens every hour... a random mob of high caliber spawns near you, either a shichibukai or a yonko (rare) or vice admiral, admiral, you get the point. It makes the mod more interesting when it's played in Singeplayer.

- Make Geppo push you forward a little bit more than pushing you upwards, It's just that I don't wanna go high and it's annoying how you geppo 5 times and you bearly get any further, because It's pushing you upwards too much.

- Maybe add more structures? Like a Marine Base, or a cave full of treasure, or a sunken ship. 

- Add blocking to the swords of the mod, also if someone hits you while you block you take a little less damage than you would if you hadn't blocked, also a spark effect and sound effect. 

- Make it so you can actually stop projectile abilities, like blow them up before they hit you, Like Imagine a Gura Gura no mi clash with Guro Guro no mi, Guro uses Raigo and Gura just destroys that shit no problem, it would make for a worthwhile fight, and a destructive one. 

- You should also buff Gura but make it's rarity almost impossible... It's funny how A random Self Proclaimed God's fruit is stronger than the STRONGEST man alive. So yeah, buff. 

- Also, add random NPCs who you can talk to in the world, add like... a lot of them... and you can talk to them about stuff and info, they might even give you a quest... like you do something for them... for money. Also, if you're a pirate and still don't have a bounty, then you shouldn't be chased by Marines... so while you don't have a bounty you can just talk to a marine and ask them if you can join the marines... same with pirates. 

- Make a rank system based on how strong you are, like it tells you if you're admiral level, Warlord level, etc. The random NPCs might treat you differently if you have these ranks, same if you have a high bounty. 

- When you pick a race, make it so your skin is actually the skin it is... like if you're a fishmen, you're blue... if you're a robot... your skin has a red eye. Stuff like that. I know there's the problem with people with skins... just replace the skins, I don't think anyone would start a riot if their minecraft skin was taken away from them... you can also make it a config option if you want. false on default. 

- Add weights you can put on your feet and arms... if you have them on your feet you'll start off slow but after a while you will start feeling normal, once you take the weights off your speed and jump will be boosted, same with the arms... you won't do much damage or move as quickly (fatigue effect) but if you have it for very long and take it off you will be stronger. 

- Make it so you can join the revolutionary Army, and go on their missions... not just Pirates and Marines and Bounty Hunters. 

- Make Bounty hunters actually go kill people with bounties on their heads, it could be a random pirate, it could be a strong one, a warlord even... very rarely a yonkou. 

- When you die your df teleports somewhere else, and once you respawn and lose your fruit you can find it again. 

- Make Devil fruits be able to be placed, I want to have a gallery of devil fruits in my base... to place them down you just shift + right click I guess. 

- Add sfx to abilities to make them sound more powerful.

- When you use observation Haki to dodge stuff or sense people... make it so your screen turns a little blue when you use it... that way its apparent that you're using haki. Same with Emperor's Haki, make it seem really powerful. 

- Add a new ability to Horo Horo no mi, where you can get out of your body and turn into a ghost and fly around and not get hurt, you have to hide your body too... so if someone finds it... u Dead. You press the ability again to go back to your body.

**Comment by LucasMeierTurtor** [comment]
Estaria bueno que el mod agregara un océano junto con islas con aldeanos y piratas que estén dispuestos a darte misiones (NPCs por el mundo), y una forma de transporte en el mar. Por ejemplo diferentes tipos de barcos que tengamos que craftear como el que viene por determinado en el minecraft.
También que para que un usuario con fruta del diablo se ahogue o no pueda salir del agua sea cuando el agua tape su cuerpo así si estamos 1 bloque sumergidos podremos salir del agua sin problemas.
