### ISSUE TITLE
SMALL SUGGESTION FOR A FRUIT

### ISSUE THREAD

**Issue by MXlordsMapone123** [Wynd/MineMineNoMi3#49]
my suggestion and add the kurozu to yami and a functionality of when a user of yami puchar another fruit user with kurozu the user would be unable to use the powers of his fruit and would give the effect of weakness

**Comment by LucasMeierTurtor** [comment]
Yo sugiero que la fruta suke suke te pueda hacer invisible hasta la ropa y armadura y que los mobs no te puedan ver siendo invisible pero que tenga una ''duración'' o que se desactive al ser dañado por cualquier entidad dentro del juego (recibir cualquier tipo de daño te quita la invisibilidad)

**Comment by LucasMeierTurtor** [comment]
Para la fruta Gura Gura no mi me gustaria que sea más destructiva o que agreguen habilidades como una que levante los bloques que estén en frente y todo lo que esté a su alcance salga volando.

**Comment by Wynd** [comment]
Added Kurouzu for Yami Yami no Mi users in 0.5.0
