### ISSUE TITLE
They mobs ando ships doesn't appear

### ISSUE THREAD

**Issue by raulsg98** [Wynd/MineMineNoMi3#5]
I downloaded the mod 1 datos ago, ir Was everything fine, Minecraft detect the game, when i Enter to the game i use creative mod to search ships or marines, pirates, mobs that appear randomly but i can't find anything, i can get all the ítems in the creative mode so i don't know what is failing or if i did something wrong

**Comment by Wynd** [comment]
closing this issue since the 0.3.0 has been released and ships do spawn in that version
