### ISSUE TITLE
How can I get the Swords in survival? 0.4.1 

### ISSUE THREAD

**Issue by LitaMasta360** [Wynd/MineMineNoMi3#51]
Hey, I like the mod, but I can't get the swords in survival mode yet, just the marine swords and Pirates Cutlass, but, you know what I mean...

**Comment by Wynd** [comment]
Currently you can't, most of them are there for servers or videos, more "basic" weapons like the jitte will be available in 0.5.0 via crafting, but don't expect Zoro's swords, those will be available later on
