### ISSUE TITLE
There are no boats after the mod is updated

### ISSUE THREAD

**Issue by MestreBrainers** [Wynd/MineMineNoMi3#52]
I already created and searched in many worlds of minecraft with this mod, and after a long time searching I found no boat in any of the worlds. I wonder if this is a bug or if you have removed the boats from the mod and if it is indeed a bug, how can I solve it?

**Comment by Wynd** [comment]
they are just very rare....you can change that from the config...I dont remember the exact option name but it should be quite obvious since it includes 'ships' in it ....anyway just change that to something around 7-15 a d you should be able to find them more easily

**Comment by Bang59** [comment]
hello, where is the file to configure? thank you

**Comment by Wynd** [comment]
.minecraft > config > mineminenomi.cfg
