### ISSUE TITLE
I can not access the gear fourth

### ISSUE THREAD

**Issue by lukarelio** [Wynd/MineMineNoMi3#54]
Hello, I was wondering how to activate the gear fourth step by step because I'm having trouble accessing? Thanks for the answer!

**Comment by LitaMasta360** [comment]
I'm not a moder, but You need to have the Bosu Haki so you can use it

**Comment by AdmiralSakazuki** [comment]
and how do I get haki xd!@??!???

**Comment by LitaMasta360** [comment]
Reaching doriki level that u need, humans:9000 fishmen:9000-9500 cyborg:8500

**Comment by Wynd** [comment]
Already answered, thanks @LitaMasta360
