### ISSUE TITLE
Crash When When starting minecraft

### ISSUE THREAD

**Issue by Spherre** [Wynd/MineMineNoMi3#56]
Hello,my game crash when i start it,so i see what the sources of the crash was,i retired mine mine no mi from my mods folder and minecraft work again so i come to you for helping
i think mine mine no mi crash with other mods so the mods i use are
SecurityCraft
Battlegear2-Bullseye
BiblioCraft
Carpenter's Blocks
CustomNPCs
Decocraft
DrZharks+MoCreatures
GollumCore Lib
IChunUtil
Jammy Furniture Reborn Mod
Mine Mine No Mi 0.4.1
And Optifine E7
Thank You for hearing me out
oh and the crash folder 
[crash-2018-12-22_19.52.24-client.txt] 
(https://github.com/Wynd/MineMineNoMi3/files/2705467/crash-2018-12-22_19.52.24-client.txt)

**Comment by Spherre** [comment]
i think the problem comes from custom npcs i used a ancient version i download the newer version and i try it

**Comment by Spherre** [comment]
nothing the game crash again

**Comment by Wynd** [comment]
Probably fixed
