### ISSUE TITLE
How do I get Haki?

### ISSUE THREAD

**Issue by AdmiralSakazuki** [Wynd/MineMineNoMi3#59]
All I'm asking is how do I get Buso/Ken/Hao Haki please someone explain because when I try to go Gear 4th its says Buso/Armament Haki is requiered so please explain to me the procedure of getting haki Thank you!

**Comment by FGpisces** [comment]
Hi, you get Buso and Ken haki by getting A LOT of Doriki (~6000 for Ken, ~8500 for Buso, but varies between races). Hao haki isn't in the game yet.

**Comment by Wynd** [comment]
Answered
