### ISSUE TITLE
Ideias about the mod

### ISSUE THREAD

**Issue by Entity321** [Wynd/MineMineNoMi3#64]
Ok, what about Some effects for some skills? I il give some Examples!

      *Gomu Gomu no mi*
Gear second: it hurts you when you use it, but it can't kill you, and if you use for too long you got frozen for some seconds.

Gear third: After used it, you got weakness and hungry effect for some secs!

Gear fourth: After using it, you also got weakness, hungry effect and freeze for some seconds, or minutes, also you cant use any haki for some secs.

  I can just think about Gomu but you can have these skills like an example from what I wanna say.

**Comment by FGpisces** [comment]
Hi, thanks for your suggestion. We plan to add negative effects for some fruits like the Gomu Gomu no Mi, and we'll do so in future updates.
