### ISSUE TITLE
can you bring Brooks Fruit in the Update? 

### ISSUE THREAD

**Issue by Dinoknower** [Wynd/MineMineNoMi3#67]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Dinoknower** [comment]
this Mod is great and i wait for my favorit Fruit the yomi yomi no mi^^ i know it is hard to make it but i think you can make it!!

**Comment by FGpisces** [comment]
We're working hard on adding all DFs, so every single one will get added eventually, don't worry ;)

**Comment by Dinoknower** [comment]
this sounds great^^
