### ISSUE TITLE
a small Suggestion for the Yomi yomi no mi

### ISSUE THREAD

**Issue by Dinoknower** [Wynd/MineMineNoMi3#70]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Dinoknower** [comment]
i have a little idea with the Ability for the Yomi yomi no mi the Brook has^^
i dont know if it possible but you could make that the Fruit activate after death and you become a Skeleton.
the Abilitys are active now because you are (u)ndead. The first Ability could be to move the Soul out of the Body and flying around and trough everything and the second Ability is to "capture other souls or Mobs and controlling them^^ (i know its hard work to realize this but i hope the ideas are not bad at all^^)

**Comment by FGpisces** [comment]
Thanks for your suggestion. The Yomi is planned to transform you into a skeleton after you die for the first time, which will also enable you to use the abilities. The soul leaving the body is currently hard to make, but will be added later.

**Comment by Wynd** [comment]
Added in 0.5.0, closing the issue
