### ISSUE TITLE
Add new mobs

### ISSUE THREAD

**Issue by BREEZEXPVP** [Wynd/MineMineNoMi3#73]
**Hi i'm detox**
i love this mod , i enjoy playing with it but its missing Mobs i know there is other mobs but "bugged" that's why i'm trying to say add new one's other then , "Smoker , mihawk ,.. and the others"

i would like to see New Ships & boats bigger then the curnet one 
Like the moby dick ship of whitebeard , and the three skull ship of blackbeard ...

with the addition of new mobs like
**WhiteBeard & blackbeard & big mom & kaido & shanks = drop devil fruit? or drop weapon**

**Same with Commanders ace , marco , vista , katakuri , oven**

or even the **Super novas**

**Comment by FGpisces** [comment]
We will add new mobs and ships when the time comes.
