### ISSUE TITLE
Bug About Stats

### ISSUE THREAD

**Issue by BREEZEXPVP** [Wynd/MineMineNoMi3#75]
**Bug Report** 
**STATS BOOl TRUE / FALSE Not Working**

**Even with the option bool to turn true & false Stats  with  KeepInv true , Stats just happend to reset to 0 with all the moves when you die even it says keep stats = true, i'm not sure but if you are fixing it in the next update then "sorry for the bug report"  i just had to say if we can enable keep stats that will be cool working feature to have !**

**Comment by Wynd** [comment]
Not really sure if this was solved or if you're still looking for an answer, but it doesn't work with true/false..the correct choices are : 
![image](https://user-images.githubusercontent.com/6152557/52999127-a650da00-342d-11e9-9a1b-7432adab2265.png)

**Comment by BREEZEXPVP** [comment]
oh okay sorry then :i didnt know that thanks i though it was true & false :)
