### ISSUE TITLE
Suggestions Part 9

### ISSUE THREAD

**Issue by Mind101** [Wynd/MineMineNoMi3#77]
so yeah... im back lets get started. 

- I have a good idea that will make kenbushoku haki work better with the suggestion I made a long time ago, the one with seeing the attack before it hits you... so pretty much in the presence of a Kenbushoku Haki user there will be a field affecting a few things... the field will affect the opponent's attacks, what I mean is that if your opponent is in that field and you have kenbushoku Haki then it will take longer for his attacks to register through, like if he right clicks his attack it will take 1 second or 4 seconds depending on your kenbushoku haki level, and in that period of time that it takes for the attack to be sent out you will see the attack in advance but sorta transparent. So in other words, Enemy is in your Kenbushoku field, his attack is sent out a second later and you see it being sent out immediately but it won't hurt you so you have time to dodge. So Enemy right clicks on his attack but it takes a second before it gets fired out, kinda like lag... but the attack WAS sent out and the enemy doesn't see it but you do, after that 1 second, the real attack gets sent out. (I'm trying to explain it better) But tbh this suggestion is only useful if you're in multiplayer, so I guess make mobs be affected by this aswell? like skeletons before they shoot their arrows...

- So for Snakeman... Now that it's been shown in the anime... Time to add it I guess? So I guess when your snakeman all your regular attacks will be changed, your pistol will become a fist that follows any enemy near you until it hits them. 

- I don't remember if I suggested this before but... Make Ice age chargeable attack, like sometimes I press it on accident and turn my whole base into ice, but if its chargeable then when you press it accidently you can stop it immediately and only a small portion of your base will turn into Ice. 

- Make it so Emperor Haki Clashes affect the stuff around you aswell.

- Also, when Emperor's Haki is used on a weak opponent... can you make it look like they actually passed out or are sleeping? kinda like in the Witchery mod with the villagers.

- Would be great if there was a dash button, Idk I just see alot of one piece characters dashing so I thought it would be good. 

- For Gearth Forth (all of them) make it so instead of jumping higher you double jump... by pressing space twice, and if you press it fast enough then you will fly.

- Maybe you can add a rage meter? If you take damage (slowly) then the meter will fill up, as it fills up you get faster and stronger... also, once its all the way up, the chance of you getting Haoshoku Haki is increased to 2%... however, if you take damage at a very rapid pace then you won't fill the rage meter and you'll just die. 

- Make it so there's different ways to get Haki, one of them I guess is to find an npc that will teach you haki, and the other way is to... find a book about haki, when you open it, it will tell you all you have to do to unlock certain Haki and also how to train them... it will be as difficult if not more than finding an npc... you can find Haki books in dungeons and stuff like that and they are pretty rare, I guess 30% chance of finding one in a dungeon or mineshaft. 

- Make it so you can train resistance... I mean... after seeing Luffy vs Katakuri... they really have alot of resistance if their fight took THIS long to conclude. Also, Add Weighted clothing to increase speed since theres really no way to increase speed other than Soru... It would be amazing if you had weighted clothing while fighting someone and you move normally and stuff, but once you take the weighted clothes off.,. then you're just waaay above the person in power.

- Add a way to increase attack damage for Devil Fruit attacks... or... literally any attack, idk... add haki to the attacks?

This is probably my shortest Suggestion Box ever... hope you enjoyed my suggestions.

**Comment by Mind101** [comment]
... ok.

**Comment by Wynd** [comment]
Closed and linked it in the "[main thread](https://github.com/Wynd/MineMineNoMi3/issues/53)"
