### ISSUE TITLE
Questions about Some Directives

### ISSUE THREAD

**Issue by SaoPig2333** [Wynd/MineMineNoMi3#78]
First of all, I would like to thank everyone in the production team. I have a question to ask, I want to give my players some skills, but how do I use instructions to give them those skills without improving Tao power? I hope to get an answer. Thank you

**Comment by AdmiralSakazuki** [comment]
oof do you have a server? if yes gimme ip so i can join I am have been looking for a good server lately so thx if you say the ip

**Comment by SaoPig2333** [comment]
I am sorry, I am a Chinese, and the server is in China. I am afraid it is difficult for you to enter my server.

**Comment by AdmiralSakazuki** [comment]
oh okay I understand thank you for replying to my comment 😃

**Comment by Wynd** [comment]
You cannot give players skills, they can only be obtained "naturally" by having the appropriate Devil Fruit or Race for that ability, closing this issue
