### ISSUE TITLE
Suggestions Part X (Finale)

### ISSUE THREAD

**Issue by Mind101** [Wynd/MineMineNoMi3#79]
alright its the finale... I'm sure you're jumping out of your seats rn.

 

- If you're a swordsman and you have a specific sword you use and never really go to any sword besides that then you will grow attached to it, it will be a part of you... so once you've used it a lot, your attack speed with that sword will slightly increase maybe by .050%...
So the more you use it, the faster and stronger it will get... as you will grow accustomed to it. 
- Since pretty soon, 1.13 forge is going to release... how about you add a feature where if you hold 2 swords... one on your main hand and the other on your other hand then you use a sword skill... it will do that skill 2 times OR it will make the skill bigger or effective. 
- Maybe in Villages there can be some "special" villagers from the mod that can sell you, Devil fruits... Idk just wanted to include this here for no reason, it just adds to the adventure aspect of the mod. 
- I don't know if this is possible, but make it so attacks can be hit by other attacks or stopped... like if someone where to throw a Raigo at you... you can stop it with 3 sword slices before it hits the ground, pretty much explodes on impact with your attack... this is good if you're fighting near an important building and you don't want it to get destroyed.
- If you pay attention, when Zoro use Armament Haki on his sword... his fist also goes black with the sword, its kinda like transferring the haki from your fist to your sword... maybe instead of just adding haki to your sword it also shows a little bit of haki on your hands? Idk just a little visual effect.
- Ok so this one will take a lot to explain... and I really like this idea so...
Alright so once you do everything for Buso Haki and get the first stage of it... you will only have access to transfer the haki to your fists/weapon... however, if you level up your buso haki more... then you will have the option to put it on another body part... pretty much, Shift and right click on the buso Haki on your action menu and a menu will show up with your character model and some little boxes... those boxes will be on body parts of your character and there will be a check mark near the box... so you can select several boxes in your model and make your whole body Haki but it'll consume a bit of your hunger as you use it, so its really recommended to put it on one spot in one move and only use full body for a "short" battle. Upon putting it on those body parts, you will get different buffs... here is a list of the buffs each body part can give you. 

Head: Once the Sniper Class gets the ability to deal more damage via headshot, this can be useful... you take little to no damage from headshots depending how strong your haki is. 
Torso: You receive little to no knockback, and you have pretty good defense.
Hands: I don't really need to explain this one...
Legs: Can add a jumpboost effect or boost some Rokushiki Techniques.
Feet: Take less fall damage, if you fall on a block from a decent height then you will break that block and maybe the others under/around it. 

- For the Buddha Fruit... when you turn into the buddha, you're very large and its harder to punch mobs that are below... so what if... your normal punches with your fist create shockwaves? No need for the abilities, the abilities do bigger shockwaves but your punches to blocks or the air will send a powerful yellow aura shockwave at your opponents, blowing them away!
- Make the Clear Clear Fruit... actually make you invisible... from Players AND Mobs... for those people who play singleplayer. 
- You said that my suggestions were a bit "unrealistic" but some of them weren't... most of them I based them off on some abilities of other mods so its not impossible but anyway... Here goes a more "realistic" suggestion for Observation Haki... 
So pretty much, the screen goes blue and you just dodge stuff... thats all. 

That's all I got. :p

**Comment by Wynd** [comment]
Just so we're clear with the "realistic" things...I'm not saying they're impossible to code...I'm saying it's gonna be difficult af for me to implement them...take the pokemons from pixelmon...they're nicely rendered in 3d with animations...those guys had their own rendering code and a lot of complex shit...is it possible ? fuck yeah it is...is it possible _for me_ to do that ? ...no...(probably never will but idk)
You also have to take into consideration how we're only 2 dudes writing code, and Caleb is still getting used with the MMnM code / forge code in general...

**Comment by Wynd** [comment]
Closed and linked it in the "[main thread](https://github.com/Wynd/MineMineNoMi3/issues/53)"
