### ISSUE TITLE
marcos fruit 

### ISSUE THREAD

**Issue by rylandaxe** [Wynd/MineMineNoMi3#80]
i cant fly with it. it feels like i should be able to fly with it considering the requirements for most of its moves... also wanna say im a huge fan of this mod its so awesome

**Comment by Wynd** [comment]
Currently it is influenced by the special flying option in the config, and that one is false by default, however the flying of Tori Tori is broken in the latest version and it will crash if used. So just having it off is easier than having the game crash each time somebody double taps space...

**Comment by rylandaxe** [comment]
i see, well that's a bummer those ships are hard to find and when i found one that was the fruit i got lol 3 day of searching. i'm a little salty xD . 

also i dont know if this is a known bug or not but when it rain's i got a permanent nauseous effect and couldn't use my devil fruit power at all even after it stop'd raining

**Comment by Wynd** [comment]
For ships you can easily just increase the ships spawn multiplier in the config to something like 7 and you'll get more ships, as for the bug...we'll test tho I'm pretty sure rain does not affect DF users, are you sure you don't have any kairoseki items in your inventory ?

**Comment by rylandaxe** [comment]
U were right I had a kairoseki item sorry my mistake. Do I need any programs to config the mod cuz I tried once before and couldn’t figure it out?

**Comment by Wynd** [comment]
notepad lol, the config is located in ./minecraft/config/mineminenomi.cfg just open it with any text editor and edit it, as a small note..edit it while the game is closed to make sure every will be correctly saved
