### ISSUE TITLE
Some Bugs and suggestions

### ISSUE THREAD

**Issue by BREEZEXPVP** [Wynd/MineMineNoMi3#81]
- "Sug" Effects like Nausea & Weakness should be removed or patched when player is near Kairoseki Ore. Also
 After use of busoshoku haki should give you weakness & hunger & slowness for like 10 sec because its easy to skip it ;) .

- "Bug"  also i have bug about when is ha ki activeted with another player GUI / ui of the combat gets glitched with devil fruits too making it to replace the fruit of the other player happend to me alot of time but didnt show any errors in the console.

- "Sug" Chests in the LargeShips should be placed in the captin room in that way players can not escape the captin and just steal the items inside the chest and run away  

- "Sug" Enable scrolling in the combat GUI , 

 that's it  . thanks alot.  good luck for the next update !

**Comment by Wynd** [comment]
- that's the idea, heavy punishment for over using those abilities, just don't stand near kairoseki blocks...it's really not that hard

- yeah I found it too a few weeks ago, it's already been solved thanks 👌 

- either way...players can just break the ship and go straight to the chests...so while I understand your logic..it wouldn't really matter for most people

- wdym exactly ? the only place where scroll would be required is for selecting abilities, and there's already a scroll bar in that UI (plus the scroll wheel also works)

**Comment by Wynd** [comment]
Everything on this list has either been added in 0.5.0 or noted so I'll be closing this issue
