### ISSUE TITLE
do u plan on adding anymore fruits?

### ISSUE THREAD

**Issue by rylandaxe** [Wynd/MineMineNoMi3#84]

**Comment by rylandaxe** [comment]
sorry to bug u again but this is the best mod i have ever played and i just want to know if your still adding to it

**Comment by Wynd** [comment]
😩 at least delete the template and leave that space empty man...
Yes...yes we are the next update was dubbed "the devil fruits update" for a reason...when I last counted there were 10 new fruits

**Comment by TheMineMan** [comment]
Sorry to intrude but do you plan on adding the Zushi Zushi no mi fruit (fujiotora Fruit) into the game just wanting to know

**Comment by Wynd** [comment]
yes...we do plan on adding as many devil fruits as possible so eventually that one will be added too

**Comment by Wynd** [comment]
Added ~16 new fruits in 0.5.0, closing this thread to keep everything nice and organized
