### ISSUE TITLE
Bug on fishman race

### ISSUE THREAD

**Issue by Inovactio** [Wynd/MineMineNoMi3#92]
**Describe the bug**
There is a bug with the fishman race, you can't swim faster as before ( previous version ) and you need to breathe.

**To Reproduce**
1. Generate a world
2. Select the fisman race
3. Try to swim
4. Try to breath

**Expected behavior**
Normally you should be able to swim faster and to breath under water. 

**Screenshots**
![2019-04-05_13 25 21](https://user-images.githubusercontent.com/49309023/55624515-7d4e9380-57a6-11e9-9e6a-16cae63f1680.png)

![2019-04-05_13 25 55](https://user-images.githubusercontent.com/49309023/55624580-b5ee6d00-57a6-11e9-8384-78a22518cb86.png)

![2019-04-05_13 26 12](https://user-images.githubusercontent.com/49309023/55624587-bbe44e00-57a6-11e9-81dd-71c494b342db.png)

![2019-04-05_13 26 22](https://user-images.githubusercontent.com/49309023/55624593-c0106b80-57a6-11e9-9198-ec6ba2073692.png)

![2019-04-05_13 26 24](https://user-images.githubusercontent.com/49309023/55624597-c4d51f80-57a6-11e9-8fd5-a8a173bd3ce2.png)

**Additional context**
I have tried to change my doriki to see if the problem was it. But the bug is still here.

**Comment by Wynd** [comment]
Amazingly written <3 with a lot of details too thanks a lot, will be fixed in 0.5.1

**Comment by Inovactio** [comment]
I study in computer science, and i have already worked with Git. I know that a very clear issue is better for developpers ;)

**Comment by Wynd** [comment]
<3 thanks a lot, and thanks for the other 2 issues as well, they'll be fixed in the next update for sure

**Comment by Wynd** [comment]
Fixed in 0.5.1. Closing issue.
