### ISSUE TITLE
Bug Sabi Sabi no mi, entities with sword can hit you.

### ISSUE THREAD

**Issue by Inovactio** [Wynd/MineMineNoMi3#94]
**Describe the bug**
The user of sabi sabi no mi can't receive damage from a sword-based attack. But it only works with other players. Entities like marine or pirate with sword can hit you.

**To Reproduce**
1. Eat the sabi sabi no mi
2. fight against an entity with sword.

**Expected behavior**
As the 0.5.0 changelog said :  " Sword-based attacks don't deal any damage and the sword loses a lot of durability when hitting "

**Screenshots**

![2019-04-07_14 59 15](https://user-images.githubusercontent.com/49309023/55683938-dbfe4380-5945-11e9-91e4-00bf9011193e.png)

![2019-04-07_14 59 24](https://user-images.githubusercontent.com/49309023/55683940-e02a6100-5945-11e9-9aeb-0714eebfdf58.png)

**Additional context**
Pigmen can't damaged you. :+1:
![2019-04-07_15 05 51](https://user-images.githubusercontent.com/49309023/55684019-c0e00380-5946-11e9-9680-1ce371ecd725.png)

**Comment by Wynd** [comment]
Fixed in 0.5.1. Closing issue.
