### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by scarybooka** [Wynd/MineMineNoMi3#99]
I think there should be an option to disable the destruction(I spam devil fruit power and realized that I destroyed my favorite island). And make Ken user be able to dodge if possible

**Comment by Wynd** [comment]
That's already a thing...in the config it's called "Enable Griefing" which is true by default, just change it to false

**Comment by scarybooka** [comment]
Oh I'm sorry thanks for the reply :) keep up the hard work
